// beam_jni.c — JNI entry points for StockApp.
// Generated by mix mob.new. Edit the two defines below; do not touch the rest.

#include <jni.h>
#include "mob_beam.h"

#define BRIDGE_CLASS  "com/mob/stock_app/MobBridge"
#define APP_MODULE    "stock_app"

JavaVM* g_jvm      = NULL;
jobject g_activity = NULL;

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    JNIEnv* env;
    (*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6);
    mob_ui_cache_class(env, BRIDGE_CLASS);
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MainActivity_nativeSetActivity(JNIEnv* env, jobject thiz, jobject activity) {
    mob_init_bridge(env, activity);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MainActivity_nativeStartBeam(JNIEnv* env, jobject thiz) {
    mob_start_beam(APP_MODULE);
}

// Called from MobBridge.nativeSendTap(handle) in Kotlin when a button is tapped.
JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendTap(JNIEnv* env, jclass cls, jint handle) {
    mob_send_tap((int)handle);
}

// Called from MobBridge.nativeSendChangeStr/Bool/Float when an input widget changes.
JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendChangeStr(JNIEnv* env, jclass cls, jint handle, jstring value) {
    const char* utf8 = (*env)->GetStringUTFChars(env, value, NULL);
    mob_send_change_str((int)handle, utf8);
    (*env)->ReleaseStringUTFChars(env, value, utf8);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendChangeBool(JNIEnv* env, jclass cls, jint handle, jboolean value) {
    mob_send_change_bool((int)handle, (int)value);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendChangeFloat(JNIEnv* env, jclass cls, jint handle, jfloat value) {
    mob_send_change_float((int)handle, (double)value);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendFocus(JNIEnv* env, jclass cls, jint handle) {
    mob_send_focus((int)handle);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendBlur(JNIEnv* env, jclass cls, jint handle) {
    mob_send_blur((int)handle);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSendSubmit(JNIEnv* env, jclass cls, jint handle) {
    mob_send_submit((int)handle);
}

// Called from MobBridge.nativeHandleBack() when the Android back gesture fires.
JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeHandleBack(JNIEnv* env, jclass cls) {
    mob_handle_back();
}

// ── Device capability result delivery ────────────────────────────────────
// Called from MobBridge when async results are ready.

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverAtom2(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    mob_deliver_atom2(pid, ca1, ca2);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverAtom3(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2, jstring a3) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    const char* ca3 = (*env)->GetStringUTFChars(env, a3, NULL);
    mob_deliver_atom3(pid, ca1, ca2, ca3);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
    (*env)->ReleaseStringUTFChars(env, a3, ca3);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverLocation(JNIEnv* env, jclass cls,
    jlong pid, jdouble lat, jdouble lon, jdouble acc, jdouble alt) {
    mob_deliver_location(pid, lat, lon, acc, alt);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverMotion(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz, jlong ts) {
    mob_deliver_motion(pid, ax, ay, az, gx, gy, gz, (long long)ts);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverFileResult(JNIEnv* env, jclass cls,
    jlong pid, jstring event, jstring sub, jstring json_items) {
    const char* ce  = (*env)->GetStringUTFChars(env, event, NULL);
    const char* cs  = (*env)->GetStringUTFChars(env, sub,   NULL);
    const char* cj  = json_items ? (*env)->GetStringUTFChars(env, json_items, NULL) : NULL;
    mob_deliver_file_result(pid, ce, cs, cj);
    (*env)->ReleaseStringUTFChars(env, event, ce);
    (*env)->ReleaseStringUTFChars(env, sub,   cs);
    if (cj) (*env)->ReleaseStringUTFChars(env, json_items, cj);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverPushToken(JNIEnv* env, jclass cls,
    jlong pid, jstring token) {
    const char* ct = (*env)->GetStringUTFChars(env, token, NULL);
    mob_deliver_push_token(pid, ct);
    (*env)->ReleaseStringUTFChars(env, token, ct);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeDeliverNotification(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_notification(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_mob_stock_1app_MobBridge_nativeSetLaunchNotification(JNIEnv* env, jclass cls,
    jstring json) {
    if (!json) { mob_set_launch_notification(NULL); return; }
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_set_launch_notification(cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}
